### ISSUE TITLE
Action triggers while no sensors are low

### ISSUE THREAD

**Issue by AllergicDuck** [tykeal/homeassistant-blueprints#2]
https://github.com/tykeal/homeassistant-blueprints/blob/fc3393e90c24bbfa249c84b5170191b8beb71384/low-battery.yaml#L81

I think the `sensors != ''''` condition doesn't correctly catches lists with no entries, my action still triggers even when no devices are under a certain battery level.

**Comment by tykeal** [comment]
@AllergicDuck did you get that by running the automation manually? I only get that if I go into the automation definition and press the 'Run Actions' option. I've played with it a few times and can only get it to trigger that condition when doing that.

If I set the battery condition to something really low and the run time to sometime close in the future for testing it doesn't give me that, and similarly if I set it the battery level to something that should cause it to trigger and also set it to a near future time it works as expected.

**Comment by Mikhail5555** [comment]
Hey @tykeal, thanks you for responding.
I did indeed test it out by using the 'Run Actions', didn't know know manually running it bypasses conditions, I guess I should read the documentation slightly better.

I guess I will give it another shot :)

**Comment by AllergicDuck** [comment]
Hey @tykeal, thank you for responding.

I did indeed run it by pressing the 'Run Actions' method. I didn't know that bypasses any condition checks, guess I should read the documentation better of automations.

I guess I will give it another try!
